# Generated by Django 5.0.2 on 2026-07-22 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkincareProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skin_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Normal"),
                            ("dry", "Dry"),
                            ("oily", "Oily"),
                            ("combination", "Combination"),
                            ("sensitive", "Sensitive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("concerns", models.TextField(blank=True)),
                ("goals", models.TextField(blank=True)),
                ("allergies", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skincare_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
