# Generated by Django 5.0.2 on 2026-07-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_inventoryitem_skincareprofile_professional_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skincareprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
